[STEP 1.2] Display query response on the page
AndreHGN/FE-Onboarding pull request #3
Opened 2021-05-28 17:32 UTC by AndreHGN

## What does this PR do?
Instead of using mock information, this PR uses the GraphQL query elaborated previously to display the desired data on the web page. Besides that small changes have been done as suggested in the previous PR: the characters' names are structured in two lists and if they overflow from the card it allows the user to scroll down/up to see the rest of the list.

2021-05-28 17:44 UTC, AndreHGN commented
Changed the page's language to english to match the data's language.

2021-05-28 23:19 UTC, lucas-eugenio requested changes
Well, the code is good. Is really well written, congrats. But, it has two problems.

The first is related to Object-Oriented Programming. if you remember your classes about this subject you will remember about Encapsulation. Encapsulation is a concept that binds together the data and functions that manipulate the data, and that keeps both safe from outside interference and misuse.

Here, we can see that *makeCard* function by itself is accessing the whole data of *episode* Object. This violates the Encapsulation. If we think in terms of responsibility it makes even less sense. What is the responsibility of *makeCard*? Create a visual element, right? So, what should be the parameters of this function? A complex object that we do not know what it has inside or just the data it has to be inside of it?

If we see the *makeGeneralInfoDiv* method it is even worse. This method, responsible of displaying just two information on the page header, is receiving the whole Query as a parameter. What makes more sense in terms of Encapsulation and Responsibility, the first or the second approach?

The second problem is in terms of User Experience (UX), you will heard this a lot! What would you think, if you access a web site like this?

![image](https://user-images.githubusercontent.com/39530109/120049358-1462af00-bff0-11eb-8380-2e1c46b12aaa.png)

I guess you would think that it is broken. We need to show to the user that something is happening. In this case, that we are making an request to the server. That is why we have all sorts of loading icons. Like this one:

![Peek 2021-05-28 20-18](https://user-images.githubusercontent.com/39530109/120049907-e8482d80-bff1-11eb-91a5-23ad96e9504f.gif)

Now it is your time. Make one!

2021-05-28 23:19 UTC, lucas-eugenio commented on src/getEpisodes.js
> +                info {
This change is correct. But, this file's alignment is wrong. Do you have Prettier installed?

The query block should be one tab right. Hehe!

2021-05-28 23:19 UTC, lucas-eugenio commented on src/makeCard.js
> +            characterListOdd.innerHTML += `<li>${character.name}</li>`
First of all, the comparisons on JS are always with three equal symbols, because of this things: https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Equality_comparisons_and_sameness

![image](https://user-images.githubusercontent.com/39530109/120047561-432a5680-bfeb-11eb-8143-ad50ae040fe4.png)

We normally do not use this kinds of if/else statements they are too long. We normally use the Conditional Ternary Operator: https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Operators/Conditional_Operator

You can see, also, that lines 32 and 35 are almost the same. In this case we normally do something like:

```
episode.characters.forEach( (character, index) => {
    const correctList = index % 2 === 0 ? characterListEven : characterListOdd
    correctList.innerHTML += `<li>${character.name}</li>`; 
});
```

2021-05-28 23:19 UTC, lucas-eugenio commented on src/makeGeneralInfoDiv.js
> +    listed.innerHTML = `Quantity of listed episodes: ${episodes.results.length}`;
I guess just "Listed episodes" works here.

2021-05-28 23:19 UTC, lucas-eugenio commented on src/printError.js
> +    gridContainer.style.justifyContent = "center";
Why are you adding this styles here instead of the CSS file?

2021-05-28 23:19 UTC, lucas-eugenio commented on src/renderData.js
> +    });
The point of an arrow function is to reduce size. You just need:

```
episodes.results.forEach(episode => gridContainer.appendChild(makeCard(episode)));
```

2021-05-28 23:19 UTC, lucas-eugenio commented on src/styles.css
> +    row-gap: 20px;
It is not related to this line, but remove the *word-break* on .card (Line 66). It is creating strange behaviors like:

![image](https://user-images.githubusercontent.com/39530109/120048092-95b84280-bfec-11eb-8ce6-bfcfa31ff672.png)

If you want to justify this content, you can add instead:

```
text-align: justify;
```

2021-05-31 20:37 UTC, lucas-eugenio approved these changes
Just fix the points I pointed out on the call and we are good to go.

With this changes, LGTM!

2021-05-31 20:37 UTC, lucas-eugenio commented on src/index.js
> +main();
I used main as an example, hehe. You can call it whatever you want! No problems with *main*, tho!

2021-05-31 20:37 UTC, lucas-eugenio commented on src/makeCard.js
> +                             <p>${episode.air_date}</p>`;
They do not need to be on separate lines. <h*>, by default, has the width: 100% style.

```
nameDateDiv.innerHTML = `<h2>${episode.episode} - ${episode.name}</h2><p>${episode.air_date}</p>`;
```

Is enough.

2021-05-31 20:37 UTC, lucas-eugenio commented on src/makeCard.js
> +        const correctList = index % 2 === 0 ? characterListEven : characterListOdd;
You can define an function called *isOdd / is Even* that makes this check and make this code cleaner.

2021-05-31 21:25 UTC, merged